apiVersion: apps/v1
kind: Deployment
metadata:
  name: svk-swapi-api
  namespace: ${ namespace }
  labels:
    app: ${manifest_app_name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${manifest_app_name}
  template:
    metadata:
      labels:
        app: ${manifest_app_name}
    spec:
      containers:
      - image: public.ecr.aws/y6q2t0j9/demos:swapi-api
        imagePullPolicy: IfNotPresent
        name: ${manifest_app_name}
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ${servicename}
  labels:
    app: ${manifest_app_name}
spec:
  type: ClusterIP
  selector:
    app: ${manifest_app_name}
  ports:
  - name: grpc
    port: 3000
    targetPort: 3000
